name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Build main app with Node 16
    - name: Setup Node.js for main app
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    
    - name: Install main app dependencies
      run: yarn install
    
    - name: Build main app
      run: yarn build
    
    - name: Install http-server
      run: npm install -g http-server
    
    - name: Start static server
      run: http-server build -p 3000 &
      
    - name: Wait for server
      run: npx wait-on http://localhost:3000
    
    # Switch to Node 22 for E2E tests
    - name: Setup Node.js for E2E tests
      uses: actions/setup-node@v4
      with:
        node-version-file: 'e2e/.nvmrc'
        cache: 'yarn'
        cache-dependency-path: 'e2e/yarn.lock'
    
    - name: Install E2E dependencies
      working-directory: ./e2e
      run: yarn install
    
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: yarn playwright install --with-deps
    
    - name: Run Playwright tests
      working-directory: ./e2e
      run: yarn playwright test
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30