name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      firebase-emulator:
        image: ghcr.io/dtinth/firebase-emulator-suite:main
        ports:
          - 9099:9099  # Authentication
          - 9000:9000  # Realtime Database
          - 8080:8080  # Firestore
          - 8085:8085  # Pub/Sub
          - 9199:9199  # Storage
          - 4000:4000  # Emulator UI
    steps:
    - uses: actions/checkout@v4
    
    # Setup Node.js 22 for both app and E2E tests
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: |
          yarn.lock
          e2e/yarn.lock
    
    - name: Install main app dependencies
      run: yarn install
    
    - name: Build main app
      run: yarn build
      env:
        CI: false  # TODO: Remove when warnings are fixed during modernization
    
    - name: Install http-server
      run: npm install -g http-server
    
    - name: Start static server
      run: http-server build -p 3000 &
      
    - name: Wait for server
      run: npx wait-on http://localhost:3000
    
    - name: Install E2E dependencies
      working-directory: ./e2e
      run: yarn install
    
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: yarn playwright install --with-deps
    
    - name: Wait for Firebase emulator
      run: npx wait-on http://localhost:9099
    
    - name: Run Playwright tests
      working-directory: ./e2e
      run: yarn playwright test
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30